name: 🐺 Snyk
on:
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    name: 🛡️ Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Snyk check
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
